name: Daily Commit Workflow

on:
  schedule:
    # Runs daily at 10:30 AM UTC
    - cron: '30 10 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git for 23f3002003@ds.study.iitm.ac.in
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "23f3002003@ds.study.iitm.ac.in"
      
      - name: Create daily commit
        run: |
          # Create or update a file with timestamp
          echo "Last updated: $(date)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily automated commit - $(date +'%Y-%m-%d %H:%M:%S')"
          git push